name: reset_provider
description: "A widget that resets it's child on request."
version: 0.1.1
repository: https://github.com/martinsellergren/reset_provider

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
