name: reset_provider
description: "A widget that resets it's child on request."
version: 0.1.0
repository: https://github.com/martinsellergren/reset_provider

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
